-- Better Auth rate-limit counters. GENERATED by the Better Auth CLI.
--
-- Stored in the database rather than in memory so the limit holds across
-- serverless instances: an in-process counter resets on every cold start, which
-- makes it close to useless for the endpoint that sends email.

create table "rateLimit" (
  "id" text not null primary key,
  "key" text not null unique,
  "count" integer not null,
  "lastRequest" bigint not null
);

create index "rateLimit_lastRequest_idx" on "rateLimit" ("lastRequest");
