import type { PrivateHostedTableRecord, PublicHostedTable } from './types'

export function toPublicHostedTable(
  record: PrivateHostedTableRecord,
): PublicHostedTable {
  const {
    id,
    slug,
    householdName,
    householdStructure,
    householdStory,
    leadHostName,
    startsAt,
    timezone,
    neighborhood,
    publicCoordinate,
    format,
    menuTitle,
    menuDescription,
    atmosphere,
    languages,
    expectedHouseholdParticipants,
    practicalInformation,
    accessibilityInformation,
    certifiedCapacity,
    availableSeats,
    minimumGuestCount,
    guaranteedOperation,
    guestPriceKurus,
    currency,
    bookingCutoffAt,
    status,
    joiningPartySummaries,
  } = record

  return {
    id,
    slug,
    householdName,
    householdStructure,
    householdStory,
    leadHostName,
    startsAt,
    timezone,
    neighborhood,
    publicCoordinate,
    format,
    menuTitle,
    menuDescription,
    atmosphere,
    languages: [...languages],
    expectedHouseholdParticipants,
    practicalInformation,
    accessibilityInformation,
    certifiedCapacity,
    availableSeats,
    minimumGuestCount,
    guaranteedOperation,
    guestPriceKurus,
    currency,
    bookingCutoffAt,
    status,
    joiningPartySummaries: [...joiningPartySummaries],
  }
}
